import { PropsWithChildren } from "react";

import type { Metadata } from "next";
import { Geist_Mono, Jersey_10 } from "next/font/google";

import { ReactQueryProvider } from "../providers";

import "@/shared/config/globals.css";

const jersey = Jersey_10({
  variable: "--font-jersey-sans",
  weight: "400",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="en">
      <body className={`${jersey.variable} ${geistMono.variable} antialiased`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
};
